services:
  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"
    restart: unless-stopped
    environment:
      NESSIE_VERSION_STORE_TYPE: JDBC2
      NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE: postgresql
      QUARKUS_DATASOURCE_POSTGRESQL_JDBC_URL: jdbc:postgresql://postgres:5432/nessie_db
      QUARKUS_DATASOURCE_POSTGRESQL_USERNAME: nessie_user
      QUARKUS_DATASOURCE_POSTGRESQL_PASSWORD: password
      QUARKUS_HTTP_PORT: 19120
    networks:
      - data-poc
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: nessie-postgres
    environment:
      POSTGRES_DB: nessie_db
      POSTGRES_USER: nessie_user
      POSTGRES_PASSWORD: password
    volumes:
      - nessie-pg-data:/var/lib/postgresql/data
    networks:
      - data-poc

networks:
  data-poc:
    external: true

volumes:
  nessie-pg-data:
