cedia:
  target: dev
  outputs:
    dev:
      type: trino
      host: trino
      port: 8083
      user: dbt
      catalog: iceberg_dev
      schema: cedia_silver_sia
      threads: 8
    prod:
      type: trino
      host: trino
      port: 8083
      user: dbt
      catalog: iceberg_prod      # 👈 catálogo prod
      schema: cedia_silver_sia   # da igual; lo sobreescribe el +schema del proyecto
      threads: 8
